"""Shared utilities used across data/training/evaluation pipelines."""

from .environment import (
    TEACHER_API_KEY_VAR,
    TEACHER_BASE_URL_VAR,
    TEACHER_PROVIDER_MODE_VAR,
    TFY_API_KEY_VAR,
    TFY_BASE_URL_VAR,
    TRUEFOUNDRY_API_KEY_VAR,
    TRUEFOUNDRY_BASE_URL_VAR,
    get_teacher_api_key,
    get_teacher_api_key_variable_name,
    get_teacher_base_url,
    get_teacher_base_url_variable_name,
    get_teacher_provider_mode,
    get_truefoundry_api_key,
    get_truefoundry_api_key_variable_name,
    get_truefoundry_base_url,
    get_truefoundry_base_url_variable_name,
    resolve_teacher_api_key,
    resolve_teacher_base_url,
    resolve_truefoundry_api_key,
    resolve_truefoundry_base_url,
)
from .experiment_tracker import (
    DEFAULT_EXPERIMENTS_ROOT,
    ExperimentTracker,
    collect_git_metadata,
    compute_dataset_checksum,
    create_experiment_tracker,
    detect_gpu_metadata,
)
from .paths import outputs_root, repo_root, reports_root

__all__ = [
    "DEFAULT_EXPERIMENTS_ROOT",
    "ExperimentTracker",
    "TEACHER_API_KEY_VAR",
    "TEACHER_BASE_URL_VAR",
    "TEACHER_PROVIDER_MODE_VAR",
    "TFY_API_KEY_VAR",
    "TFY_BASE_URL_VAR",
    "TRUEFOUNDRY_API_KEY_VAR",
    "TRUEFOUNDRY_BASE_URL_VAR",
    "collect_git_metadata",
    "compute_dataset_checksum",
    "create_experiment_tracker",
    "detect_gpu_metadata",
    "get_teacher_api_key",
    "get_teacher_api_key_variable_name",
    "get_teacher_base_url",
    "get_teacher_base_url_variable_name",
    "get_teacher_provider_mode",
    "get_truefoundry_api_key",
    "get_truefoundry_api_key_variable_name",
    "get_truefoundry_base_url",
    "get_truefoundry_base_url_variable_name",
    "repo_root",
    "resolve_teacher_api_key",
    "resolve_teacher_base_url",
    "resolve_truefoundry_api_key",
    "resolve_truefoundry_base_url",
    "reports_root",
    "outputs_root",
]
