"""Core schema contracts for synthetic data generation pipelines."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

TaskMode = Literal["diagnose", "teach", "quiz_feedback"]
SplitHint = Literal["train", "validation", "test", "heldout_benchmark"]
FallacyLabel = str
FilterDecisionLabel = Literal["pass", "reject", "needs_revision"]
ValidationSeverity = Literal["error", "warning"]


@dataclass(frozen=True)
class PromptContext:
    """Inputs used to render a prompt template."""

    fallacy_label: FallacyLabel | None
    is_no_fallacy: bool
    task_mode: TaskMode
    difficulty_level: Literal["beginner", "intermediate", "advanced"] | None = None
    domain_tag: str | None = None
    analogy_source_domain: str | None = None
    analogy_target_domain: str | None = None
    reflection_style_tag: str | None = None
    is_adversarial: bool = False
    adversarial_type: str | None = None
    attack_target: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class BehaviorOutput:
    """Structured behavior-spec-aligned output fields."""

    fallacy_hypothesis: str
    reasoning_diagnosis: str
    analogy_source_scenario: str
    analogy_mapping: str
    analogy_limits: str
    repair: str
    confidence_note: str


@dataclass(frozen=True)
class CandidateExample:
    """Draft candidate generated by the teacher system."""

    example_id: str
    generation_run_id: str
    source_id: str
    argument_text: str
    task_mode: TaskMode
    difficulty_level: Literal["beginner", "intermediate", "advanced"] | None
    primary_fallacy_label: FallacyLabel | None
    acceptable_alternative_labels: tuple[FallacyLabel, ...] = ()
    is_no_fallacy: bool = False
    behavior_output: BehaviorOutput | None = None
    expected_sections: tuple[str, ...] = ()
    required_behaviors: tuple[str, ...] = ()
    prohibited_behaviors: tuple[str, ...] = ()
    rubric_hooks: tuple[str, ...] = ()
    domain_tag: str | None = None
    analogy_source_domain: str | None = None
    analogy_target_domain: str | None = None
    reflection_style_tag: str | None = None
    is_adversarial: bool = False
    adversarial_type: str | None = None
    attack_target: str | None = None
    created_at: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class CritiqueResult:
    """Structured critique emitted by the critic/refiner stage."""

    example_id: str
    critique_id: str
    score_by_dimension: dict[str, float]
    findings: tuple[str, ...] = ()
    revision_instructions: tuple[str, ...] = ()
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class FilterDecision:
    """Quality filter decision for one candidate."""

    example_id: str
    decision: FilterDecisionLabel
    reason_codes: tuple[str, ...]
    scores: dict[str, float] = field(default_factory=dict)
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class DedupDecision:
    """Deduplication outcome for one candidate."""

    example_id: str
    kept: bool
    dedup_cluster_id: str | None = None
    similarity_score: float | None = None
    reason: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class ValidationIssue:
    """Schema/policy issue raised during dataset validation."""

    example_id: str | None
    severity: ValidationSeverity
    code: str
    message: str
    field: str | None = None


@dataclass(frozen=True)
class ValidationReport:
    """Dataset validation result container."""

    total_examples: int
    passed_examples: int
    failed_examples: int
    issues: tuple[ValidationIssue, ...]


@dataclass(frozen=True)
class DatasetRecord:
    """Final validated export-ready dataset record."""

    example_id: str
    split_hint: SplitHint | None
    dataset_version: str
    taxonomy_version: str
    source_id: str
    argument_text: str
    task_mode: TaskMode
    difficulty_level: Literal["beginner", "intermediate", "advanced"] | None
    primary_fallacy_label: FallacyLabel | None
    acceptable_alternative_labels: tuple[FallacyLabel, ...]
    is_no_fallacy: bool
    expected_sections: tuple[str, ...]
    required_behaviors: tuple[str, ...]
    prohibited_behaviors: tuple[str, ...]
    rubric_hooks: tuple[str, ...]
    domain_tag: str | None
    analogy_source_domain: str | None
    analogy_target_domain: str | None
    reflection_style_tag: str | None
    is_adversarial: bool
    adversarial_type: str | None
    attack_target: str | None
    generator_model_id: str
    critic_model_id: str | None
    template_id: str
    template_version: str
    prompt_seed: int | None
    decoding_config: dict[str, Any]
    critique_scores: dict[str, float]
    filter_decisions: tuple[str, ...]
    dedup_cluster_id: str | None
    validation_status: Literal["passed", "failed"]
    created_at: str
    updated_at: str
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class DatasetManifest:
    """Manifest metadata for exported dataset artifacts."""

    dataset_name: str
    dataset_version: str
    snapshot_hash: str
    taxonomy_version: str
    prompt_bundle_version: str
    teacher_config_version: str
    generation_run_id: str
    total_examples: int
    no_fallacy_examples: int
    adversarial_examples: int
    fallacy_counts: dict[str, int]
    domain_counts: dict[str, int]
    reflection_style_counts: dict[str, int]
    created_at: str
    metadata: dict[str, Any] = field(default_factory=dict)
